VMS_DIGLAB/VMS_DIGLAB/Controllers/AdminController.cs
using DigiFoodLabServiceCore;
using Microsoft.Azure.ActiveDirectory.GraphClient;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading.Tasks;
using System.Web.Mvc;
using VMS_DIGLAB.Filters;
using VMS_DIGLAB.Models;
using VMS_DIGLAB.ViewModel;
using VMSServiceCore;

namespace VMS_DIGLAB.Controllers
{
    [Authorize]
    [Admin]
    [ApplicationVariables]
    public class AdminController : Controller
    {
        //public string staffId { get; set; }

        public string staffId
        {
            get
            {
                return Session["StaffId"].ToString();
            }
        }
        public string fullName
        {
            get
            {
                return Session["FullName"].ToString();
            }
        }

        //Get Index
        public ActionResult Index()
        {
            return RedirectToAction("DashBoard");
        }

        
        public AdminController()
        {
            IUser user = Task.Run(() => AdService.GetCurrentUser()).Result;
            string email = user.UserPrincipalName;

            string staffId = email.Split(new Char[] { '@' })[0];

        }

        //GET Admin/DashBoard

        public ActionResult DashBoard()
        {
            StaffDashboardViewModel dashBoardItems = new StaffDashboardViewModel();
            try
            {
                string classMethod = "/Admin/Dashboard";

                //get total visitor count

                Dictionary<string, dynamic> sqlParameters = new Dictionary<string, dynamic>();
                var totalVisitors = Utilities.EnCapriDisco_Select2("GetTotalVisitors", sqlParameters, classMethod, "");
                // var totalVisitors = Utilities.EnCapriDisco_Select2("GetTotalVisitors", "@BranchName");

                if (totalVisitors.Rows.Count > 0)
                {
                    foreach (DataRow row in totalVisitors.Rows)
                    {
                        dashBoardItems.TotalVisitors = Convert.ToInt32(row["TotalVisitors"].ToString());
                    }
                }


                //get most recent staff visitors

                sqlParameters.Add("@count", 5);

                var mostRecentVisitors = Utilities.EnCapriDisco_Select2("GetAllMostRecentVisitors", sqlParameters, classMethod, "");


                List<Visitor> visitors = new List<Visitor>();
                if (mostRecentVisitors.Rows.Count > 0)
                {


                    foreach (DataRow row in mostRecentVisitors.Rows)
                    {
                        visitors.Add(
                            new Visitor
                            {
                                Email = row["Email"].ToString(),
                                VisitorFullName = row["VisitorFullName"].ToString(),
                                VisitImage = row["VisitImage"].ToString()
                            }
                        );
                    }

                }
                dashBoardItems.MostRecentVisitors = visitors;

                //get total visitors signed in today
                Dictionary<string, dynamic> sqlParameters2 = new Dictionary<string, dynamic>();
                var totalSignedInVistorsToday = Utilities.EnCapriDisco_Select2("GetTotalVisitorsSignedInToday", sqlParameters2, classMethod, "");


                if (totalVisitors.Rows.Count > 0)
                {
                    foreach (DataRow row in totalSignedInVistorsToday.Rows)
                    {
                        dashBoardItems.TotalSignedInVisitorToday = Convert.ToInt32(row["StaffVisitorCount"].ToString());
                    }
                }


                //get total appointments today

                DataTable totalAppointmentsToday = Utilities.EnCapriDisco_Select2("GetTotalVisitorsOnAppointmentToday", sqlParameters2, classMethod, "");


                if (totalAppointmentsToday.Rows.Count > 0)
                {
                    foreach (DataRow row in totalAppointmentsToday.Rows)
                    {
                        dashBoardItems.TotalAppointmentsToday = Convert.ToInt32(row["StaffVisitorCount"].ToString());
                    }
                }
            }
            catch (Exception ex)
            {
                ErrHandler.WriteError("Error getting dashboard items", ex.Message + "|" + Utilities.GetIP());
            }




            return View(dashBoardItems);
        }
        // GET: Receptionist/CreateInvite
        public ActionResult CreateInvite()
        {
            return View();
        }

        // Admin/VisitorLog
        public ActionResult VisitorLog()
        {
            string classMethod = "/Admin/VisitorLog";

            List<VisitorViewModel> visitors = new List<VisitorViewModel>();



            try
            {
                Dictionary<string, dynamic> sqlParameters = new Dictionary<string, dynamic>();
                var resp = Utilities.EnCapriDisco_Select2("GetAllVisitors", sqlParameters, classMethod, "");

                foreach (DataRow row in resp.Rows)
                {
                    visitors.Add(new VisitorViewModel
                    {
                        //BranchName = row["BranchName"].ToString(),
                        VisitorCompany = row["VisitorCompany"].ToString(),
                        Email = row["Email"].ToString(),
                        VisitorFullName = row["VisitorFullName"].ToString(),
                        VisitorPhoneNumber = row["VisitorPhoneNumber"].ToString(),
                        //VisitTime = row["VisitTime"].ToString(),
                        TimeIn = row.Field<DateTime>("TimeIn"),
                        TimeOut = row.Field<DateTime?>("TimeOut"),
                        Purpose = (AppointmentPurpose)Convert.ToInt32(row["Purpose"].ToString()),
                        VisitImage = row["VisitImage"].ToString()
                    }
                    
                    );
                }

                var count = visitors.Count;
            }
            catch (Exception ex)
            {
                //return an error page
                ErrHandler.WriteError(classMethod + " unable to connect to DB. " + ex.Message, "");
            }

            return View(visitors);
        }
    }
}

VMS_DIGLAB/VMS_DIGLAB/Controllers/ReceptionistController.cs
using DigiFoodLabServiceCore;
using Microsoft.Azure.ActiveDirectory.GraphClient;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Net;
using System.Security.Claims;
using System.Text;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using VMS_DIGLAB.Filters;
using VMS_DIGLAB.Models;
using VMS_DIGLAB.ViewModel;
using VMSServiceCore;

namespace VMS_DIGLAB.Controllers
{
    [Authorize]
    [Receptionist]
    [ApplicationVariables]
    public class ReceptionistController : Controller
    {
        //public string staffId { get; set; }

        public string staffId
        {
            get
            {
                return Session["StaffId"].ToString();
            }
        }
        public string fullName
        {
            get
            {
                return Session["FullName"].ToString();
            }
        }
        private readonly ApplicationDbContext db = new ApplicationDbContext();
        // GET: Receptionist/Index
        public ActionResult Index()
        {
            return View();
        }

        public ReceptionistController()
        {
            //string[] staff = System.Web.HttpContext.Current.Request.LogonUserIdentity.Name.Split(new Char[] { '\\', '\\' });
            //staffId = System.Web.HttpContext.Current.Request.LogonUserIdentity.Name.Substring(13);//staff[1];

            //IUser user = Task.Run(() => AdService.GetCurrentUser()).Result;
            //string email = user.UserPrincipalName;

            //string staffId = email.Split(new Char[] { '@' })[0];

        }

        // GET: Receptionist/SignIn
        public ActionResult SignIn()
        {
            SignInViewModel signInModel = new SignInViewModel();
            return View();
        }

        // GET: Receptionist/SignIn
        [HttpPost]
        public ActionResult SignIn(Visitor visitor)
        {
            string classMethod = "receptionist/signin";
            //visitor.AppointmentId = 1;
            string staffId = string.Empty;
            string code = "XX";
            string message = "Failure";
            try
            {
                
                if (visitor == null)
                {
                    code = "01";
                    message = "Bad input";
                }

                if (!ModelState.IsValid)
                {
                    StringBuilder strError = new StringBuilder();
                    var errors = ModelState.Values.SelectMany(x => x.Errors);

                    if (errors.Any())
                    {
                        string error = string.Empty;
                        foreach (ModelError item in errors)
                        {
                            error = string.IsNullOrEmpty(item.ErrorMessage) ? item.Exception.Message : item.ErrorMessage;
                            strError.Append(error + "|");
                        }
                        message = strError.ToString().TrimEnd('|');
                        code = "02";

                    }
                }
                else
                {
                    if (visitor.IsAppointment == true)
                    {
                        try
                        {
                            var resp = Utilities.EnCapriDisco_Select(visitor.AppointmentId, "", "GetAppointmentDetailsByAppointmentId", "@AppointmentId");

                            if (resp.Rows.Count == 0)
                            {

                            }
                            else
                            {
                                foreach (DataRow row in resp.Rows)
                                {

                                    staffId = row["StaffId"].ToString();
                                    
                                }
                            }

                            


                        }
                        catch (Exception ex)
                        {
                            ErrHandler.WriteLog("appointments/detail/" + " " + ex.Message, Utilities.GetIP());

                        }
                    }
                    else
                    {
                        staffId = visitor.HostId;
                    }
                    //create parameters to create new users
                    Dictionary<string, dynamic> sqlParameters = new Dictionary<string, dynamic>();
                    sqlParameters.Add("@StaffId", staffId);
                    sqlParameters.Add("@VisitorFullName", visitor.VisitorFullName);
                    sqlParameters.Add("@VisitorPhoneNumber", visitor.VisitorPhoneNumber);
                    sqlParameters.Add("@BranchName", visitor.BranchName);
                    sqlParameters.Add("@VisitorImage", visitor.VisitorImage);
                    sqlParameters.Add("@VisitorCompany", visitor.VisitorAddress);
                    sqlParameters.Add("@AppointmentId", visitor.IsAppointment == true?  visitor.AppointmentId : 1);
                    sqlParameters.Add("@Purpose", visitor.Purpose);
                    sqlParameters.Add("@LaptopName", visitor.LaptopName);
                    sqlParameters.Add("@SerialNumber", visitor.SerialNumber);
                    sqlParameters.Add("@Email", visitor.Email);
                    sqlParameters.Add("@IsAppointment", visitor.IsAppointment);
                    sqlParameters.Add("@TagNumber", visitor.TagNumber);
                    sqlParameters.Add("@HasDevice", visitor.HasDevice);
                    sqlParameters.Add("@DeviceType", visitor.DeviceType);
                    sqlParameters.Add("@DeviceColour", visitor.DeviceColour);
                    sqlParameters.Add("@DeviceName", visitor.DeviceName);
                    sqlParameters.Add("@VisitImage", visitor.VisitImage);

                    //call the stored procedure passing the parameters in
                    int result = Utilities.EnCapriDisco_Insert("CreateNewVisitor", sqlParameters, classMethod, staffId);

                    if (Math.Abs(result) == 0)
                    {
                        code = "03";
                        message = "Error updating the visitor record";
                    }
                    else
                    {
                        if(visitor.IsAppointment == true)
                        {
                            try
                            {

                                Dictionary<string, dynamic> newSqlParameters = new Dictionary<string, dynamic>();

                                newSqlParameters.Add("@AppointmentId", visitor.AppointmentId);
                                newSqlParameters.Add("@AppointmentAction", 2);

                                int result2 = Utilities.EnCapriDisco_Insert("ChangeAppointmentStatus", newSqlParameters, $"appointments/SIGNIN/{visitor.AppointmentId}", Utilities.GetIP());
                                if (Math.Abs(result2) > 0)
                                {
                                    code = "00";
                                    message = "Successful";
                                }
                                else
                                {
                                    code = "00";
                                    message = "Partial success";
                                }

                            }
                            catch (Exception ex)
                            {
                                ErrHandler.WriteError("Error occured updating trying to update the database", ex.Message);
                            }
                        }
                        else
                        {
                            code = "00";
                            message = "Successful";
                        }
                        
                    }
                }
            }
            catch (Exception ex)
            {
                ErrHandler.WriteError("Error creating a new user ---"+ ex.Message , staffId);
                code = "04";
                message = "Error occured signing visitor in the visitor record";

            }
            //ErrHandler.WriteError("Error creating a new user ---" + , staffId);
            return Json(new { code, message });
        }

        public bool IsVisitorSignedIn(string tagNumber)
        {
            try
            {
                var signedInUser = Utilities.EnCapriDisco_Select(tagNumber, "", "VisitorSignedInByTagNumber", "@TagNumber");
                if (signedInUser.Rows.Count > 0)
                {
                    return true;
                }
            }
            catch (Exception ex)
            {

                ErrHandler.WriteError("Error getting getting if visitor by tagnumber", ex.Message + "|" + Utilities.GetIP());
            }
            return false;
        }
        // GET: Receptionist/SignOut
        public ActionResult SignOut()
        {

            return View();
        }


        [HttpPost]
        public ActionResult SignOut(SignOutViewModel viewModel)
        {
            var classMethod = "Receptionist/SignOut";

            if (ModelState.IsValid)
            {
                try
                {
                    bool isVisitorSignedInAlready = IsVisitorSignedIn(viewModel.TagNumber);

                    if (isVisitorSignedInAlready == false)
                    {
                        ViewBag.Status = "Not Ok";
                        ViewBag.Message = "No user is not signed out with the tag number";
                    }
                    else
                    {
                        Dictionary<string, dynamic> sqlParameters = new Dictionary<string, dynamic>();
                        sqlParameters.Add("@TagNumber", viewModel.TagNumber);

                        int result = Utilities.EnCapriDisco_Insert("SignOutVisitor", sqlParameters, classMethod, viewModel.TagNumber);

VMS_DIGLAB/VMS_DIGLAB/Views/Shared/FAQ.cshtml
@{
    Layout = null;
}

<!doctype html>
<html lang="en" dir="ltr">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <meta name="msapplication-TileColor" content="#0061da">
    <meta name="theme-color" content="#1643a3">
    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <meta name="HandheldFriendly" content="True">
    <meta name="MobileOptimized" content="320">
    <link rel="icon" href="favicon.ico" type="image/x-icon" />
    <link rel="shortcut icon" type="image/x-icon" href="favicon.ico" />

    <!-- Title -->
    <title>trueVisit</title>
    <link rel="stylesheet" href="assets/fonts/fonts/font-awesome.min.css">

    <!-- Font Family-->
    <link href="https://fonts.googleapis.com/css?family=Poppins:200,300,400,500,600,700" rel="stylesheet">

    <!-- Dashboard Css -->
    <link href="~/Content/assets/css/dashboard.css" rel="stylesheet" />

    <!-- c3.js Charts Plugin -->
    <link href="~/Content/assets/plugins/charts-c3/c3-chart.css" rel="stylesheet" />

    <!-- Custom scroll bar css-->
    <link href="~/Content/assets/plugins/scroll-bar/jquery.mCustomScrollbar.css" rel="stylesheet" />

    <!---Font icons-->
    <link href="~/Content/assets/plugins/iconfonts/plugin.css" rel="stylesheet" />
    <link href="~/Content/assets/plugins/iconfonts/icons.css" rel="stylesheet" />
</head>

<body class="">
    <div id="global-loader"></div>
    <div class="page">
        <div class="page-main">
            <div class="header py-4">
                <div class="container">
                    <div class="d-flex">
                        <a class="header-brand" href="index.html">
                            <img src="~/Content/assets/images/brand/fidelity.png" class="header-brand-img" alt="trueVisit Logo">
                        </a>
                        <div class=" ">
                            <form class="input-icon mt-1 ">
                                <div class="input-icon-addon">
                                    <i class="fe fe-search"></i>
                                </div>
                                <input type="search" class="form-control header-search" placeholder="Search&hellip;" tabindex="1">
                            </form>
                        </div>
                        @Html.Partial("_StaffProfile")
                        <a href="#" class="header-toggler d-lg-none ml-3 ml-lg-0" data-toggle="collapse" data-target="#headerMenuCollapse">
                            <span class="header-toggler-icon"></span>
                        </a>
                    </div>
                </div>
            </div>
            <div class="Klast-navbar" id="headerMenuCollapse">
                <div class="container">
                    <ul class="nav">
                        <li class="nav-item">
                            <a class="nav-link" href="dashboard.html">
                                <i class="ti ti-home"></i>
                                <span> Dashboard</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="appointment.html"><i class="ti ti-calendar"></i> <span>Make an Appointment</span></a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" href="manage_appointment.html"><i class="ti ti-pencil"></i> <span>Manage Appointments</span></a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" href="visitor_log.html"><i class="ti ti-face-smile"></i><span>Visitor Log</span></a>
                        </li>

                    </ul>
                </div>
            </div>
            <!-- End of Menu -->
            <div class="about-img">
                <div class="card-body p-8 align-items-center text-center">
                    <h2 class="text-white display-5 font-weight-semibold">FAQ</h2>
                    <p class="text-white"> Got questions? Don't worry, we've got you covered</p>
                </div>
            </div>

            <div class="my-3 my-md-5">

                <div class="container">
                    <div class="page-header">
                        <h4 class="page-title">Frequently Asked Questions</h4>
                    </div>
                    <div class="row ">
                        <div class="col-md-12">
                            <div class="card">
                                <div class="card-body">
                                    <h4 class="font-weight-semibold">How To Insert All The Plugins?</h4>
                                    <p>I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness. No one rejects, dislikes, or avoids pleasure itself, because it is pleasure, but because those who do not know how to pursue pleasure rationally encounter consequences</p>
                                </div>
                                <div class="card-body ">
                                    <h4 class="font-weight-semibold">How Can I contact?</h4>
                                    <p>I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness. No one rejects, dislikes, or avoids pleasure itself, because it is pleasure, but because those who do not know how to pursue pleasure rationally encounter consequences</p>
                                </div>
                                <div class="card-body">
                                    <h4 class="font-weight-semibold">Can I use the appointment module?</h4>
                                    <p>I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness. No one rejects, dislikes, or avoids pleasure itself, because it is pleasure, but because those who do not know how to pursue pleasure rationally encounter consequences</p>
                                </div>
                                <div class="card-body ">
                                    <h4 class="font-weight-semibold">How Can I see reports and statistics?</h4>
                                    <p>I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness. No one rejects, dislikes, or avoids pleasure itself, because it is pleasure, but because those who do not know how to pursue pleasure rationally encounter consequences</p>
                                </div>
                                <div class="card-body">
                                    <h4 class="font-weight-semibold">It is Easy to downloadable?</h4>
                                    <p>I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness. No one rejects, dislikes, or avoids pleasure itself, because it is pleasure, but because those who do not know how to pursue pleasure rationally encounter consequences</p>
                                </div>
                                <div class="card-body ">
                                    <h4 class="font-weight-semibold">How can I send feedback?</h4>
                                    <p>I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness. No one rejects, dislikes, or avoids pleasure itself, because it is pleasure, but because those who do not know how to pursue pleasure rationally encounter consequences</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>

        <!--footer-->
        <footer class="footer">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-lg-4 col-sm-12  col-md-5 mt-3 mt-lg-0 text-center d-none d-md-block">
                        <div class="social">
                            <ul class="text-center">
                                <li>
                                    <a class="social-icon" href="#"><i class="fa fa-facebook"></i></a>
                                </li>
                                <li>
                                    <a class="social-icon" href="#"><i class="fa fa-twitter"></i></a>
                                </li>
                                <li>
                                    <a class="social-icon" href="#"><i class="fa fa-youtube"></i></a>
                                </li>
                                <li>
                                    <a class="social-icon" href="#"><i class="fa fa-linkedin"></i></a>
                                </li>
                                <li>
                                    <a class="social-icon" href="#"><i class="fa fa-google-plus"></i></a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-lg-8 col-sm-12 col-md-7 mt-3 mt-lg-0 text-center">
                        Copyright © 2018 <a href="#">trueVisit</a>. With <i class="fa fa-heart blink text-danger"></i> from <a class="text-success" href="#">Fidelity Bank Digital LAB</a> All rights reserved.
                    </div>
                </div>
            </div>
        </footer>
        <!-- End Footer-->
    </div>

    <!-- Dashboard js -->
    <script src="~/Content/assets/js/vendors/jquery-3.2.1.min.js"></script>
    <script src="~/Content/assets/js/vendors/bootstrap.bundle.min.js"></script>
    <script src="~/Content/assets/js/vendors/jquery.sparkline.min.js"></script>
    <script src="~/Content/assets/js/vendors/selectize.min.js"></script>
    <script src="~/Content/assets/js/vendors/jquery.tablesorter.min.js"></script>
    <script src="~/Content/assets/js/vendors/circle-progress.min.js"></script>
    <script src="~/Content/assets/plugins/rating/jquery.rating-stars.js"></script>
    <!-- Custom scroll bar Js-->
    <script src="~/Content/assets/plugins/scroll-bar/jquery.mCustomScrollbar.concat.min.js"></script>

    <!-- Custom Js-->
    <script src="~/Content/assets/js/custom.js"></script>
</body>

</html>

VMS_DIGLAB/VMS_DIGLAB/Views/Shared/_AdminMenuBar.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="header py-4">
    <div class="container">
        <div class="d-flex">
            <a class="header-brand" href="~/staff/index">
                <img src="~/Content/assets/images/brand/fidelity.png" class="header-brand-img" alt="trueVisit logo">
            </a>
            <!--<div class="d-flex d-none">
                <form class="input-icon mt-1 ">
                    <div class="input-icon-addon">
                        <i class="fe fe-search"></i>
                    </div>
                    <input type="search" class="form-control header-search" placeholder="Search&hellip;" tabindex="1">
                </form>
            </div>-->

            @Html.Partial("_StaffProfile")
            <a href="#" class="header-toggler d-lg-none ml-3 ml-lg-0" data-toggle="collapse" data-target="#headerMenuCollapse">
                <span class="header-toggler-icon"></span>
            </a>
        </div>
    </div>
</div>

<div class="Klast-navbar" id="headerMenuCollapse">
    <div class="container">
        <ul class="nav">
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("dashboard", "Admin")">
                    <i class="ti ti-home"></i>
                    <span> Dashboard</span>
                </a>
            </li>
            <li>
                <a class="nav-link" href="@Url.Action("VisitorLog", "Admin")"><i class="ti ti-face-smile"></i><span>Visitor Log</span></a>
            </li>


        </ul>
    </div>
</div>
@RenderBody()

VMS_DIGLAB/VMS_DIGLAB/Views/Shared/_ReceptionistMenuBar.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<div class="header py-4">
    <div class="container">
        <div class="d-flex">
            <a class="header-brand" href="@Url.Action("Index", "Receptionist")">
                <img src="~/Content/assets/images/brand/fidelity.png" class="header-brand-img" alt="trueVisit logo">
            </a>
            <!--<div class="d-flex d-none">
                <form class="input-icon mt-1 ">
                    <div class="input-icon-addon">
                        <i class="fe fe-search"></i>
                    </div>
                    <input type="search" class="form-control header-search" placeholder="Search&hellip;" tabindex="1">
                </form>
            </div>-->

            @Html.Partial("_StaffProfile")
            <a href="#" class="header-toggler d-lg-none ml-3 ml-lg-0" data-toggle="collapse" data-target="#headerMenuCollapse">
                <span class="header-toggler-icon"></span>
            </a>
        </div>
    </div>
</div>
<div class="Klast-navbar" id="headerMenuCollapse">
    <div class="container">
        <ul class="nav">
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("dashboard", "staff")"><i class="fe fe-home"></i><span style="font-size:20px">Go to My Portal</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("dashboard", "receptionist")"><i class="fe fe-trending-up"></i><span>Statistics</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("signin", "receptionist")"><i class="fe fe-user-plus"></i> <span>Sign In</span></a>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("signout", "receptionist")"><i class="fe fe-user-x"></i> <span>Sign Out</span></a>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("appointments", "receptionist")"><i class="fe fe-watch"></i><span>Appointments</span></a>
            </li>


        </ul>
    </div>
</div>
<!-- End of Menu -->

@RenderBody()